=== sergiopalmero87/actividad2/biblioteca_documentos_2.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <annotation>
        <documentation>Esquema que marca la estructura de una biblioteca de documentos</documentation>
    </annotation>

<!-- Creamos elemento biblioteca_documentos-->
    <element name="biblioteca_documentos">
        <complexType>

        <!-- Creamos la secuencia con los elementos que hay dentro: Libro, Revista, Periódico-->
            <sequence>

            <!-- Creamos elemento libro con todos sus subelementos, atributos y restricciones-->
                <element name="Libro" minOccurs="1" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="titulo">
                                <simpleType>
                                    <restriction base="string">
                                        <maxLength value="25"></maxLength>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="capitulos">
                                <complexType>
                                    <sequence>
                                        <element name="capitulo">
                                            <complexType>
                                                <sequence>
                                                    <element name="titulo" type="string"></element>
                                                </sequence>
                                                <attribute name="num_paginas_capitulo" type="integer"></attribute>
                                            </complexType>
                                        </element>
                                        <element name="contenido">
                                            <complexType>
                                                <attribute name="enlace" type="string"></attribute>
                                            </complexType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="indice" type="string"></element>
                            <element name="sinopsis" type="string"></element>
                        </sequence>
                        <attribute name="libro_id">
                            <simpleType>
                                <restriction base="string"><pattern value="[L][-][0-9]{4}"></pattern></restriction>
                            </simpleType>
                        </attribute>
                        <attribute name="tipo_clase" use="required">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="novela"></enumeration>
                                    <enumeration value="didáctico"></enumeration>
                                    <enumeration value="infantil"></enumeration>
                                </restriction>
                            </simpleType>
                        </attribute>
                        <attribute name="num_paginas" type="integer" use="required"></attribute>
                    </complexType>
                </element>

                <!-- Creamos elemento revista con sus subelementos, atributos y restricciones-->
                <element name="revista" minOccurs="1" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="titulo">
                                <simpleType>
                                    <restriction base="string"> 
                                        <maxLength value="25"></maxLength>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="numero_revista" type="integer"></element>
                            <element name="indice" type="string"></element>
                            <element name="seccion" >
                                <complexType>
                                    <sequence>
                                        <element name="titulo_seccion"></element>
                                        <element name="contenido">
                                            <complexType>
                                                <attribute name="enlace" type="string"></attribute>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="num_paginas_seccion" type="integer" use="required"></attribute>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="revista_id" use="required">
                            <simpleType>
                                <restriction base="string">
                                    <pattern value="[R][-][0-9]{4}"></pattern>
                                </restriction>
                            </simpleType>   
                        </attribute>
                        <attribute name="tipo_clase" use="required">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="informática"></enumeration>
                                    <enumeration value="corazón"></enumeration>
                                    <enumeration value="coches"></enumeration>
                                    <enumeration value="investigación"></enumeration>
                                    <enumeration value="otras"></enumeration>
                                </restriction>
                            </simpleType>
                        </attribute>
                        <attribute name="numero_paginas" type="integer" use="required"></attribute>
                    </complexType>
                </element>

                <!-- Creamos elemento periódico con sus subelementos, atributos y restricciones-->
                <element name="periodico" minOccurs="1" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="seccion">
                                <complexType>
                                    <sequence>
                                        <element name="articulos">
                                            <complexType>
                                                <attribute name="nombre_autor" type="string" use="required"></attribute>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="tipo_seccion" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <pattern value="economia"></pattern>
                                                <pattern value="deportes"></pattern>
                                                <pattern value="nacional"></pattern>
                                                <pattern value="internacional"></pattern>
                                            </restriction>
                                        </simpleType>   
                                    </attribute>
                                </complexType>
                            </element>
                            <element name="indice" type="string"></element>
                            <element name="contenido">
                                <complexType>
                                    <attribute name="enlace" type="string"></attribute>
                                </complexType>  
                            </element>
                        </sequence>
                        <attribute name="periodico_id" use="required">
                            <simpleType>
                                <restriction base="string">
                                    <pattern value="[P][-][0-9]{4}"></pattern>
                                </restriction>
                            </simpleType>
                        </attribute>
                        <attribute name="tipo_clase" use="required">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="nacional"></enumeration>
                                    <enumeration value="internacional"></enumeration>
                                </restriction>
                            </simpleType>
                        </attribute>
                        <attribute name="fecha_publicacion" type="date" use="required"></attribute>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== sergiopalmero87/actividad2/biblioteca_documentos_2.xml
<?xml version="1.0" encoding="UTF-8"?>    
<biblioteca_documentos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                       xsi:noNamespaceSchemaLocation= "biblioteca_documentos_2.xsd">

    <Libro libro_id="L-0001" tipo_clase="novela" num_paginas="70">
        <titulo> Viaje a Egipto</titulo>
        <capitulos>
            <capitulo>
                <titulo>Nos vamos</titulo>
            </capitulo>
            <contenido enlace="enlace"/> 
        </capitulos>
        <indice>Indice del libro</indice>
        <sinopsis>Sinopsis del libro</sinopsis>
    </Libro>
    
    <Libro libro_id="L-0002" tipo_clase="didáctico" num_paginas="77">
        <titulo> Aprendiendo XML</titulo>
        <capitulos>
            <capitulo>
                <titulo>Ya sabes. Eres un máquina</titulo>
            </capitulo>
            <contenido enlace="enlace"/> 
        </capitulos>
        <indice>Indice del libro</indice>
        <sinopsis>Sinopsis del libro</sinopsis>
    </Libro>
    

    <revista revista_id="R-0001" tipo_clase="coches" numero_paginas="25">
        <titulo>Revista coches</titulo>
        <numero_revista>3</numero_revista>
        <indice>Indice de la revista</indice>
        <seccion num_paginas_seccion="4">
            <titulo_seccion>Ferrari volador</titulo_seccion>
            <contenido enlace="enlace"/>
        </seccion>
    </revista>

    <revista revista_id="R-0002" tipo_clase="informática" numero_paginas="35">
        <titulo>Últimos avances con IA</titulo>
        <numero_revista>3</numero_revista>
        <indice>Indice de la revista</indice>
        <seccion num_paginas_seccion="4">
            <titulo_seccion>¿Qué puede hacer Chatgpt?</titulo_seccion>
            <contenido enlace="enlace"/>
        </seccion>
    </revista>


    <periodico periodico_id="P-0001" tipo_clase="nacional" fecha_publicacion="2023-05-12">
        <seccion tipo_seccion="deportes">
            <articulos nombre_autor="Sergio"/>
        </seccion>
        <indice> Indice del periódico</indice>
        <contenido enlace="enlace"/>
    </periodico>

    <periodico periodico_id="P-0002" tipo_clase="internacional" fecha_publicacion="2023-05-13">
        <seccion tipo_seccion="economia">
            <articulos nombre_autor="Pepito"/>
        </seccion>
        <indice> Indice del periódico</indice>
        <contenido enlace="enlace"/>
    </periodico>

</biblioteca_documentos>
