=== sergiopalmero87/actividad2/Biblioteca_Christian/biblioteca.dtd
<!ELEMENT biblioteca (libro+, revista+, periódico+)>

<!ELEMENT libro (título, capítulo+, índice, sinopsis)>
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro tipo_clase (novela | infantil | didáctico) #REQUIRED >

<!ELEMENT título (#PCDATA)>
<!ATTLIST título páginas CDATA #REQUIRED>

<!ELEMENT capítulo (título_capítulo, contenido)>
<!ATTLIST capítulo páginas CDATA #REQUIRED>
<!ATTLIST contenido enlace CDATA #REQUIRED>

<!ELEMENT título_capítulo (#PCDATA)>
<!ELEMENT contenido EMPTY>
<!ELEMENT índice (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

<!ELEMENT revista (título_revista, número_revista, índice_revista, seccion_revista+)>
<!ATTLIST revista id ID #REQUIRED >
<!ATTLIST revista tipo_clase (informática | corazón | coches | investigación | otras) #REQUIRED >
<!ATTLIST revista número_páginas CDATA #REQUIRED >

<!ELEMENT título_revista (#PCDATA)>
<!ELEMENT número_revista (#PCDATA)>
<!ELEMENT índice_revista (#PCDATA)>
<!ELEMENT seccion_revista (título_sección, contenido_revista)>
<!ELEMENT título_sección (#PCDATA)>
<!ELEMENT contenido_revista EMPTY>

<!ATTLIST seccion_revista páginas CDATA #REQUIRED >
<!ATTLIST contenido_revista enlace CDATA #REQUIRED >

=== sergiopalmero87/actividad2/Biblioteca_Christian/biblioteca_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">

<biblioteca>
    <libro id="L0001" tipo_clase= "novela" páginas="891">
        <título>El Señor de los Anillos</título>
        <capítulo páginas="16">
            <título_capítulo>Una reunión muy esperada</título_capítulo>
            <contenido enlace="enlace del capítulo"></contenido>
        </capítulo>
        <capítulo páginas="17">
            <título_capítulo>La sombra del pasado</título_capítulo>
            <contenido enlace="enlace del capítulo"></contenido>
        </capítulo>
        <capítulo páginas="16">
            <título_capítulo>Tres es compañia</título_capítulo>
            <contenido enlace="enlace del capítulo"></contenido>
        </capítulo>
        <capítulo páginas="9">
            <título_capítulo>un atajo hacia los hongos</título_capítulo>
            <contenido enlace="enlace del capítulo"></contenido>
        </capítulo>
        <índice>Índice del libro</índice>
        <sinopsis>En la adormecida e idílica Comarca, un joven hobbit recibe un encargo: custodiar el Anillo Único y emprender el viaje para su destrucción en las Grietas del Destino. 
        Consciente de la importancia de su misión, Frodo abandona la Comarca e inicia el camino hacia Mordor con la compañía de inesperada de Sam, Pippin y Merry.  
        Pero sólo con la ayuda de Aragorn conseguirán vencer a los Jinetes Negros y alcanzar el refugio de la Casa de Elrond en Rivendel.
        </sinopsis>    
    </libro>
     <libro id="L0002" tipo_clase= "didáctico" páginas="644">
        <título>Código Limpio: Manual de estilo para el desarrollo ágil de software</título>
        <capítulo páginas="20">
            <título_capítulo>Código Limpio</título_capítulo>
            <contenido enlace="enlace del capítulo"></contenido>
        </capítulo>
        <capítulo páginas="18">
            <título_capítulo>Nombres con sentido</título_capítulo>
            <contenido enlace="enlace del capítulo"></contenido>
        </capítulo>
        <capítulo páginas="27">
            <título_capítulo>Funciones</título_capítulo>
            <contenido enlace="enlace del capítulo"></contenido>
        </capítulo>
        <capítulo páginas="26">
            <título_capítulo>Comentarios</título_capítulo>
            <contenido enlace="enlace del capítulo"></contenido>
        </capítulo>
        <índice>Índice del libro</índice>
        <sinopsis>Cada año, se invierten innumerables horas y se pierden numerosos recursos debido a código mal escrito, ralentizando el desarrollo, disminuyendo la productividad, generando graves fallos e incluso pudiendo acabar con la organización o empresa. 
        El reconocido experto de software Robert C. Martin, junto con sus colegas de Object Mentor, nos presentan sus óptimas técnicas y metodologías ágiles para limpiar el código sobre la marcha y crearlo de forma correcta, de este modo mejorará como programador. 
        Esta obra se divide en tres partes. La primera describe los principios, patrones y prácticas para crear código limpio. La segunda incluye varios casos de estudio cuya complejidad va aumentando. Cada ejemplo es un ejercicio de limpieza y transformación 
        de código con problemas. La tercera parte del libro contiene una lista de heurística y síntomas de código erróneo (smells) confeccionada al crear los casos prácticos. El resultado es una base de conocimientos que describe cómo pensamos cuando creamos, 
        leemos y limpiamos código. Imprescindible para cualquier desarrollador, ingeniero de software, director de proyectos, jefe de equipo o analista de sistemas interesado en crear código de mejor calidad. ¡El libro que todo programador debe leer!</sinopsis>    
    </libro>

    <revista id="R0001" tipo_clase="coches" número_páginas="56">
        <título_revista>Revista de coches</título_revista>
        <número_revista>12</número_revista>
        <índice_revista>Índice de la revista</índice_revista>
        <seccion_revista páginas="8">
            <título_sección>Prueba de la semana</título_sección>
            <contenido_revista enlace="enlace a la información"></contenido_revista>    
        </seccion_revista>
        <seccion_revista páginas="5">
            <título_sección>Reportaje Mercedes G63 AMG</título_sección>
            <contenido_revista enlace="enlace a la información"></contenido_revista>    
        </seccion_revista>
        <seccion_revista páginas="3">
            <título_sección>Mantenimiento mensual</título_sección>
            <contenido_revista enlace="enlace a la información"></contenido_revista>    
        </seccion_revista>
        <seccion_revista páginas="2">
            <título_sección>Publireportaje</título_sección>
            <contenido_revista enlace="enlace a la información"></contenido_revista>    
        </seccion_revista>
    </revista>

    <revista id="R0002" tipo_clase="informática" número_páginas="40">
        <título_revista>Revista de informática</título_revista>
        <número_revista>37</número_revista>
        <índice_revista>Índice de la revista</índice_revista>
        <seccion_revista páginas="3">
            <título_sección>Placas base ASUS explotan</título_sección>
            <contenido_revista enlace="enlace a la información"></contenido_revista>    
        </seccion_revista>
        <seccion_revista páginas="3">
            <título_sección>Nvidia no escucha a los consumidores</título_sección>
            <contenido_revista enlace="enlace a la información"></contenido_revista>    
        </seccion_revista>
        <seccion_revista páginas="4">
            <título_sección>Beta abierta de Diablo IV este fin de semana</título_sección>
            <contenido_revista enlace="enlace a la información"></contenido_revista>    
        </seccion_revista>
        <seccion_revista páginas="2">
            <título_sección>Publireportaje</título_sección>
            <contenido_revista enlace="enlace a la información"></contenido_revista>    
        </seccion_revista>
    </revista>

    <periódico id="P0001" tipo_clase="nacional" fecha_publicación="11/05/2023">
        <sección_periódico tipo_sección="económica">
            <artículo autor="Federico">
                <contenido_periódico información="enlace a la información"></contenido_periódico>
            </artículo>
        </sección_periódico>
        <índice_periódico>Índice del periódico</índice_periódico>    
    </periódico>

    <periódico id="P0002" tipo_clase="nacional" fecha_publicación="10/05/2023">
        <sección_periódico tipo_sección="deportes">
            <artículo autor="Alfgredo Relaño">
                <contenido_periódico información="enlace a la información"></contenido_periódico>
            </artículo>
        </sección_periódico>
        <índice_periódico>Índice del periódico</índice_periódico>    
    </periódico>

    <periódico id="P0003" tipo_clase="internacional" fecha_publicación="09/05/2023">
        <sección_periódico tipo_sección="económica">
            <artículo autor="Marc Vidal">
                <contenido_periódico información="enlace a la información"></contenido_periódico>
            </artículo>
        </sección_periódico>
        <índice_periódico>Índice del periódico</índice_periódico>    
    </periódico>
</biblioteca>
